version: "3.8"

services:
  nos-server-cpu:
    image: autonomi/nos:latest-cpu
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    ipc: host
