default_language_version:
  python: python3.9

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autofix suggestions'

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.7.0]
      args: [--max-line-length=120, --extend-ignore=E203, --extend-ignore=W503]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    - id: nbstripout

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-ast
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key      # check for private keys
    - id: end-of-file-fixer
    - id: pretty-format-json
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=100']
      exclude: ^tests/test_data
    - id: requirements-txt-fixer
      files: requirements.*\.txt$

  # In order to follow native namespace packages from PEP 420, we have
  # to avoid __init__.py under the base package autonomi, so that
  # other submodules such as autonomi.client can also be added under
  # the same namepace.
  - repo: local
    hooks:
    - id: ensure-no-init-file
      name: ensure-no-init-file
      entry: bash -c 'if [[ -f autonomi/__init__.py ]]; then exit 1; fi'
      language: system
      types: [python]
      pass_filenames: false
