version: "3.8"

services:
  nos-server:
    image: autonomi/nos:latest-gpu
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TARGET=gpu
        - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
    command: nos-grpc-server
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=DEBUG
      - NOS_SHM_ENABLED=1
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
