version: "3.8"

x-nos-common:
  &nos-common-test
  volumes:
    - ~/.nosd:/app/.nos
    - /dev/shm:/dev/shm
  environment:
    - NOS_LOGGING_LEVEL=DEBUG
  shm_size: 4G

x-nos-gpu:
  &nos-common-gpu-test
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  test-cpu:
    <<: *nos-common-test
    build:
      context: .
      dockerfile: docker/Dockerfile.cpu
      target: test-cpu
    command: ${DOCKER_CMD:-make test-cpu}

  test-gpu:
    <<: [*nos-common-test, *nos-common-gpu-test]
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
      target: test-gpu
    command: ${DOCKER_CMD:-make test-gpu}
