version: "3.8"

x-nos-common-gpu:
  &nos-common-gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  grpc-server:
    # <<: *nos-common-gpu
    image: autonomi-ai/nos:latest-gpu-base
    # entrypoint: bash # python -m nos.experimental.grpc.grpc_server
    # command: grpc-serve
    command: bash
    network_mode: host
    environment:
      - NOS_HOME=/data/nos
      - NOS_LOGGING=DEBUG
    volumes:
      - ~/.nos:/data/nos
      - /tmp:/tmp
