version: "3.8"
services:
  grpc-server:
    image: autonomi/nos:latest-gpu
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TARGET=gpu
        - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
    entrypoint: nos-grpc-server
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=DEBUG
    volumes:
      - ~/.nosd:/app/.nos
      - /tmp/docker:/tmp
    shm_size: 4G
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
