version: "3.8"

x-nos-common:
  &nos-common
  volumes:
    - ~/.nosd:/app/.nos
    - ${PWD}:/app/nos
  environment:
    - NOS_LOGGING_LEVEL=DEBUG
  shm_size: 4G

x-nos-gpu:
  &nos-common-gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  base-gpu:
    <<: [*nos-common, *nos-common-gpu]
    image: autonomi/nos:latest-gpu
    # pull_policy: missing
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile
    #   args:
    #     - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
    #     - TARGET=gpu
    #     - DOCKER_TARGET=base

  trt-dev:
    <<: [*nos-common, *nos-common-gpu]
    image: autonomi/nos:latest-trt-dev
    # pull_policy: missing
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile.trt
    #   args:
    #     - BASE_IMAGE=autonomi/nos:latest-gpu
    #     - DOCKER_TARGET=trt-dev
    # depends_on:
    #   - base-gpu
    command: ${DOCKER_CMD:-pytest -sv tests/models/test_object_detection.py -k test_object_detection_predict_one}

  mmdet-dev:
    <<: [*nos-common, *nos-common-gpu]
    image: autonomi/nos:latest-mmdet-dev
    pull_policy: missing
    # build:
    #   context: .
    #   dockerfile: docker/Dockerfile.mmdet
    #   args:
    #     - BASE_IMAGE=autonomi/nos:latest-gpu
    # depends_on:
    #   - base-gpu

  test-mmdet-dev:
    <<: [*nos-common, *nos-common-gpu]
    image: autonomi/nos:latest-mmdet-dev
    command: ${DOCKER_CMD:-pytest -sv tests/models/openmmlab}
