version: "3.8"

services:
  grpc-server:
    image: autonomi-ai/nos:latest-gpu
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - BASE_IMAGE=nvidia/cuda:11.8.0-runtime-ubuntu22.04
    entrypoint: nos-grpc-server
    network_mode: host
    environment:
      - NOS_HOME=/data/nos
      - NOS_LOGGING=DEBUG
    volumes:
      - ~/.nos:/data/nos
      - /tmp:/tmp
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
