version: "3.8"
services:
  grpc-server:
    image: autonomi-ai/nos:latest-gpu
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TARGET=gpu
        - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
    entrypoint: nos-grpc-server
    network_mode: host
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING=DEBUG
    volumes:
      - ~/.nos_docker:/app/.nos
      - /tmp/docker:/tmp
    shm_size: 2G
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
