version: "3.8"

x-nos-common:
  &nos-common-test
  volumes:
    - ~/.nosd:/app/.nos
    - /tmp/docker:/tmp
    - /dev/shm:/dev/shm
  environment:
    - NOS_LOGGING=DEBUG
  shm_size: 4G

x-nos-gpu:
  &nos-common-gpu-test
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  test-cpu:
    <<: *nos-common-test
    image: autonomi/nos:latest-cpu-test
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: test
      args:
        - TARGET=cpu
        - BASE_IMAGE=python:3.8.10-slim
    command: ${DOCKER_CMD:-make test-cpu}

  test-gpu:
    <<: [*nos-common-test, *nos-common-gpu-test]
    image: autonomi/nos:latest-gpu-test
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: test
      args:
        - TARGET=gpu
        - BASE_IMAGE=nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ${DOCKER_CMD:-make test-gpu}
