version: "3.8"
services:
  grpc-server:
    image: autonomi-ai/nos:latest-cpu
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - TARGET=cpu
        - BASE_IMAGE=python:3.8.10-slim
    entrypoint: nos-grpc-server
    network_mode: host
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING=DEBUG
    volumes:
      - ~/.nos_docker:/app/.nos
      - /tmp/docker:/tmp
    shm_size: 4G
