version: "3.8"
services:
  grpc-server:
    image: autonomi/nos:0.0.0-cpu
    command: nos-grpc-server
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
    volumes:
      - ~/.nosd:/app/.nos
      - tmp:/tmp
    shm_size: 4G
volumes:
  tmp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=8G,uid=1000