spillai:
  name: Sudeep Pillai
  description: NOS Core Developer
  avatar: https://github.com/spillai.png

outtanames:
  name: Scott Loftin
  description: NOS Core Developer
  avatar: https://github.com/outtanames.png
