authors:
  spillai:
    avatar: https://github.com/spillai.png
    description: NOS Core Developer
    name: Sudeep Pillai
  outtanames:
    avatar: https://github.com/outtanames.png
    description: NOS Core Developer
    name: Scott Loftin
