version: "3.8"

services:
  nos-http-proxy:
    image: autonomi/nos:latest-gpu
    command: nos-http-server
    ports:
      - 8000:8000
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
      - NOS_HTTP_PORT=8000
      - NOS_HTTP_MAX_WORKER_THREADS=4
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    network_mode: host
    ipc: host
    depends_on:
      - nos-server-gpu

  nos-server-gpu:
    image: autonomi/nos:latest-gpu
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
