version: "3.8"

services:
  nos-http-proxy:
    image: autonomi/nos:latest-cpu
    command: nos-http-server --port 80
    ports:
      - 8000:80
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
      - NOS_HTTP_PORT=8000
      - NOS_HTTP_MAX_WORKER_THREADS=4
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    network_mode: host
    ipc: host
    depends_on:
      - nos-server-cpu

  nos-server-cpu:
    image: autonomi/nos:latest-cpu
    ports:
      - 50051:50051
    environment:
      - NOS_HOME=/app/.nos
      - NOS_LOGGING_LEVEL=INFO
    volumes:
      - ~/.nosd:/app/.nos
      - /dev/shm:/dev/shm
    ipc: host
