name: GPU Benchmarks

on:
  push:
    branches: [main]
  workflow_call:

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  docker-test-gpu-benchmark:
    name: Self-hosted Test env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: self-hosted
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          auto-update-conda: true
          activate-environment: nos-${{ matrix.os }}-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          use-mamba: true
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/nos-${{ matrix.os }}-${{ matrix.python-version }}
          key: conda-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('conda/envs/base-gpu/env.yml') }}-${{ hashFiles('pyproject.toml') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Install dependencies (GPU)
        run: make develop
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Quality Check
        run: make lint
      - name: Test (GPU)
        run: make test-benchmarks
