name: CPU Tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  test-cpu:
    name: Test CI (CPU)
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          auto-update-conda: true
          activate-environment: nos-${{ matrix.os }}-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          use-mamba: true
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/nos-${{ matrix.os }}-${{ matrix.python-version }}
          key: conda-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements/requirements.txt') }}-${{ hashFiles('pyproject.toml') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ env.CACHE_NUMBER }}
      - name: Install dependencies
        run: make develop-cpu
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Quality Check
        run: make lint
      - name: Test
        run: make test-cpu

  docker-test-cpu:
    name: Test CI within docker (CPU)
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - name: Build and test-cpu within docker container
        run: make docker-test-cpu
