name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

jobs:
  setup-miniconda-env:
    name: Test env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # , "macos-latest", "windows-latest"
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          activate-environment: nos-${{ matrix.os }}-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          # environment-file: conda/envs/base-cpu/env.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        run: make develop-cpu
      - name: Quality Check
        run: make style
      - name: Test
        run: make test-cpu
