name: Publish Docker and Pypi

on:
    workflow_run:
      workflows: ["Release Tests"]
      types:
        - completed

jobs:
  push_cpu_gpu_to_registry:
    name: Push CPU/GPU Docker image to Docker Hub
    runs-on: large_runner
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install agi-pack
        run: pip install agi-pack

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build CPU/GPU Docker images
        run: make docker-build-cpu docker-build-gpu
      - name: Push CPU/GPU Docker images
        run: make docker-push-cpu docker-push-gpu

      - name: Install dependencies
        run: make develop-cpu
      - name: Build pypi packages
        run: make dist
      - name: Publish pypi packages
        run: make -f makefiles/Makefile.admin.mk create-pypi-release PYPI_USERNAME=${{ secrets.PYPI_USERNAME }} PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}

  push_cu118_to_registry:
    needs: push_cpu_gpu_to_registry
    name: Push cu118 / cu121 Docker image to Docker Hub
    runs-on: large_runner
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install agi-pack
        run: pip install agi-pack

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build cu118 / cu121 Docker images
        run: make docker-build-cu118 docker-build-cu121
      - name: Push cu118 / cu121 Docker images
        run: make docker-push-cu118 docker-push-cu121

  # push_multiplatform_to_registry:
  #   needs: push_multiplatform_to_registry
  #   name: Push multiplatform Docker image to Docker Hub
  #   runs-on: large_runner
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and Push multiplatform Docker images
  #       run: make docker-build-and-push-multiplatform-cpu-prod
