name: Publish Docker and Pypi

on:
    workflow_run:
      workflows: ["Release Tests"]
      types:
        - completed

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: make docker-build-all
      - name: Push docker images
        run: make docker-push-all

      - name: Install dependencies
        run: make develop-cpu
      - name: Build pypi packages
        run: make dist
      - name: Publish pypi packages
        run: make -f makefiles/Makefile.admin.mk create-pypi-release-loose PYPI_USERNAME=${{ secrets.PYPI_USERNAME }} PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
