name: Publish Docker image

on:
   release:
     types: [prereleased]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: make .docker-build TARGET=test DOCKER_TARGET=server BASE_IMAGE=python:3.8.10-slim
      - name: Push docker image
        run: make .docker-push-base TARGET=test
