name: Publish Docker image

on:
   release:
     types: [prereleased]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # - name: Run CI tests
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #    workflow: integrations.yml

      - name: Check out the repo
        uses: actions/checkout@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Docker images
      #   run: make docker-build-all
      # - name: Push docker images
      #   run: make docker-push-all

      - name: Build pypi packages
        run: make dist
      - name: Publish pypi packages
        run: make -f makefiles/Makefile.admin.mk create-pypi-release-test
