name: Generate / Deploy Docs

on:
  push:
    branches: [main]
  release:
    types: [released]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install '.[docs]'
      - run: cp docs/CNAME .
      - run: mkdocs gh-deploy --force
