name: Pull request comment to run e2e tests
on:
  issue_comment:
    types: [created, edited]

jobs:
  call-benchmark:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: Trigger benchmark workflow
        uses: ./.github/workflows/e2e
        if: contains(github.event.comment.body, '/e2e') && github.event.issue.pull_request    # check if the comments come from pull request, exclude those from issue.
